# -*- coding: utf-8 -*-
"""vip.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OSsc_fd_sKcEbc5I1_Y4IFIhiltL6Ttw
"""

import pandas as pd
from numpy import nan

#Read file
mentors = pd.read_csv('https://raw.githubusercontent.com/cgadwa1/vipList/master/vipForG.csv')
vips = pd.read_csv('https://raw.githubusercontent.com/cgadwa1/vipList/master/vipForG2.csv')

#Renamed columns 
mentors = mentors[['Last Name', 'First Name']]
mentors.rename(columns={'Last Name':'last_name', 'First Name': 'first_name'}, inplace=True)

vips = vips[['Last Name', 'First Name']]
vips.rename(columns={'Last Name':'last_name', 'First Name': 'first_name'}, inplace=True)

#Merged two tables
result = pd.merge(mentors, vips, on='last_name', how='left')
result = result[['last_name', 'first_name_x', 'first_name_y']]

#Made vip column more meaningful 
result.rename(columns={'last_name':'last_name', 'first_name_x': 'first_name', 'first_name_y': 'vip'}, inplace=True)
result['vip'] = result['vip'].fillna('No')

for i in result.index:
    if result.at[i, 'vip'] != 'No':
        result.at[i, 'vip'] = "Yes"

result.head(30)